<?php
class Social extends CakeMigration {

/**
 * Migration description
 *
 * @var string
 */
	public $description = '';

/**
 * Actions to be performed
 *
 * @var array $migration
 */
	public $migration = array(
		'up' => array(
			'create_table' => array(
				'battle_logs' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index', 'comment' => '攻撃側'),
					'target' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index', 'comment' => '防御側(敵ID)'),
					'result' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'comment' => '1:攻撃側勝利 2:攻撃側敗北'),
					'log' => array('type' => 'text', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'FK_battle_logs_users' => array('column' => 'user_id', 'unique' => 0),
						'FK_battle_logs_users_2' => array('column' => 'target', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'card_groups' => array(
					'card_group_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'evol_group' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 8, 'key' => 'index'),
					'card_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index'),
					'prev' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'comment' => '前の進化のcard_group_id'),
					'next' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'comment' => '次の進化のcard_group_id'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'indexes' => array(
						'PRIMARY' => array('column' => 'card_group_id', 'unique' => 1),
						'group_id' => array('column' => 'evol_group', 'unique' => 0),
						'FK_card_groups_cards' => array('column' => 'card_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'cards' => array(
					'card_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'card_name' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'card_title' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'comment' => '肩書き', 'charset' => 'utf8'),
					'height' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'comment' => '身長'),
					'weight' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'comment' => '体重'),
					'size' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'comment' => '3サイズ', 'charset' => 'utf8'),
					'blood' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'comment' => '血液型', 'charset' => 'utf8'),
					'rare_level' => array('type' => 'integer', 'null' => false, 'default' => '1', 'length' => 3, 'comment' => 'レアリティ 1:N 2:HN 3:R 4:HR 5:SR'),
					'card_cost' => array('type' => 'integer', 'null' => false, 'default' => '1', 'length' => 5, 'comment' => 'デッキ設置に必要なコスト'),
					'attr' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'comment' => '1:愛 2:舞 3:魅'),
					'card_hp' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'card_atk' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'card_def' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'card_level' => array('type' => 'integer', 'null' => false, 'default' => '20', 'length' => 8, 'comment' => 'カード最大レベル'),
					'skill_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index'),
					'card_words' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 250, 'collate' => 'utf8_general_ci', 'comment' => 'セリフ', 'charset' => 'utf8'),
					'card_detail' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 250, 'collate' => 'utf8_general_ci', 'comment' => '解説', 'charset' => 'utf8'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'indexes' => array(
						'PRIMARY' => array('column' => 'card_id', 'unique' => 1),
						'FK_mst_cards_mst_skill' => array('column' => 'skill_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'enemys' => array(
					'enemy_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'card_name' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'hp' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'atk' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'def' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'skill_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index', 'comment' => 'スキルID'),
					'skill_level' => array('type' => 'integer', 'null' => false, 'default' => '20', 'length' => 10),
					'before_words' => array('type' => 'text', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'comment' => '戦闘前セリフ', 'charset' => 'utf8'),
					'after_win_words' => array('type' => 'text', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'comment' => 'プレイヤーが勝ったとき', 'charset' => 'utf8'),
					'after_lose_words' => array('type' => 'text', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'comment' => 'プレイヤーが負けたとき', 'charset' => 'utf8'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 4),
					'indexes' => array(
						'PRIMARY' => array('column' => 'enemy_id', 'unique' => 1),
						'FK_enemys_skills' => array('column' => 'skill_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'errors' => array(
					'error_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'message' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 300, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 4),
					'indexes' => array(
						'PRIMARY' => array('column' => 'error_id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'ev_item_probs' => array(
					'ev_item_prob_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'item_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'key' => 'index'),
					'ev_stage_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5),
					'prob' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'comment' => '同一item_idの合算が分母'),
					'kind' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'comment' => '1:card 2:item 3:money'),
					'target' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5),
					'num' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'indexes' => array(
						'PRIMARY' => array('column' => 'ev_item_prob_id', 'unique' => 1),
						'FK_ev_item_probs_items' => array('column' => 'item_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'ev_quests' => array(
					'ev_quest_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 5, 'key' => 'primary'),
					'ev_quest_title' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'ev_quest_detail' => array('type' => 'text', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'detail_before1' => array('type' => 'text', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'detail_before2' => array('type' => 'text', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'detail_after' => array('type' => 'text', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 4),
					'start_time' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'end_time' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'ev_quest_id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'ev_stage_probs' => array(
					'ev_stage_prob_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'ev_stage_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 8, 'key' => 'index'),
					'kind' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'comment' => '1:card 2:item 3:money 4:enemy'),
					'target' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'comment' => '対象のID'),
					'num' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'comment' => '数量'),
					'prob' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'indexes' => array(
						'PRIMARY' => array('column' => 'ev_stage_prob_id', 'unique' => 1),
						'FK_ev_stage_probs_ev_stages' => array('column' => 'ev_stage_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'ev_stages' => array(
					'ev_stage_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 8, 'key' => 'primary'),
					'ev_quest_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'key' => 'index'),
					'ev_stage_title' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'use_act' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'comment' => '消費行動力'),
					'prob_get' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'comment' => '何かを取得する確率'),
					'enemy_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index', 'comment' => 'ステージのボス'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'indexes' => array(
						'PRIMARY' => array('column' => 'ev_stage_id', 'unique' => 1),
						'FK_ev_stages_enemys' => array('column' => 'enemy_id', 'unique' => 0),
						'FK_ev_stages_ev_quests' => array('column' => 'ev_quest_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'ev_user_cur_stages' => array(
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'primary'),
					'ev_stage_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 8, 'key' => 'index'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'user_id', 'unique' => 1),
						'FK_user_cur_stages_stages' => array('column' => 'ev_stage_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'friends' => array(
					'friend_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'primary', 'comment' => 'user_id2人を結ぶ'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'primary'),
					'state' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'comment' => '1:申請 2:申請取下 3:拒否 4:承認済'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => array('friend_id', 'user_id'), 'unique' => 1),
						'FK_friends_users' => array('column' => 'user_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'gacha_probs' => array(
					'gacha_prob_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'gacha_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'key' => 'index'),
					'card_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index'),
					'prob' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'comment' => '合算した値が分母になる'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'indexes' => array(
						'PRIMARY' => array('column' => 'gacha_prob_id', 'unique' => 1),
						'FK_mst_gacha_probs_mst_gachas' => array('column' => 'gacha_id', 'unique' => 0),
						'FK_mst_gacha_probs_mst_cards' => array('column' => 'card_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'gachas' => array(
					'gacha_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 5, 'key' => 'primary'),
					'gacha_name' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'gacha_detail' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 250, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'start_time' => array('type' => 'datetime', 'null' => false, 'default' => '0000-00-00 00:00:00'),
					'end_time' => array('type' => 'datetime', 'null' => false, 'default' => '3000-01-01 00:00:00'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 4),
					'indexes' => array(
						'PRIMARY' => array('column' => 'gacha_id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'item_effects' => array(
					'item_effect_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 5, 'key' => 'primary'),
					'item_effect_detail' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 250, 'collate' => 'utf8_general_ci', 'comment' => '使用前の説明', 'charset' => 'utf8'),
					'detail_after' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 250, 'collate' => 'utf8_general_ci', 'comment' => '使用後の説明', 'charset' => 'utf8'),
					'effect' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'comment' => '1:act 2:bp 3.カード出現率アップ 4.金庫出現率アップ 5.クエストの全力進行アップ'),
					'percent' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'comment' => '回復の割合'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'indexes' => array(
						'PRIMARY' => array('column' => 'item_effect_id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'item_probs' => array(
					'item_prob_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'item_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'key' => 'index'),
					'stage_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'key' => 'index'),
					'prob' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'comment' => '同一item_idの合算が分母'),
					'kind' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'comment' => '1:card 2:item 3:money'),
					'target' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5),
					'num' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'indexes' => array(
						'PRIMARY' => array('column' => 'item_prob_id', 'unique' => 1),
						'FK_mst_item_probs_mst_items' => array('column' => 'item_id', 'unique' => 0),
						'FK_item_probs_stages' => array('column' => 'stage_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'items' => array(
					'item_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 5, 'key' => 'primary'),
					'item_name' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'item_detail' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 250, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'point' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'money' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'item_effect_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'key' => 'index'),
					'box_num' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'comment' => '0以上でボックスアイテムの当選個数'),
					'item' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'key' => 'index', 'comment' => 'ボックスアイテムの場合開ける為に必要なアイテム'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 3),
					'indexes' => array(
						'PRIMARY' => array('column' => 'item_id', 'unique' => 1),
						'FK_items_items' => array('column' => 'item_effect_id', 'unique' => 0),
						'FK_items' => array('column' => 'item', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'messages' => array(
					'message_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index'),
					'target_user' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index'),
					'kind' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'comment' => '１:友達申請 2:友達承認 3:挨拶'),
					'message' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 300, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 4),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'message_id', 'unique' => 1),
						'user_user_target' => array('column' => array('user_id', 'target_user'), 'unique' => 0),
						'FK_messages_users_2' => array('column' => 'target_user', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'news' => array(
					'news_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'news_title' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'news_detail' => array('type' => 'text', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'start_time' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'end_time' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 3),
					'indexes' => array(
						'PRIMARY' => array('column' => 'news_id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'quests' => array(
					'quest_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 5, 'key' => 'primary'),
					'quest_title' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'quest_detail' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 400, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'detail_before1' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 300, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'detail_before2' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 250, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'detail_after' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 1000, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'indexes' => array(
						'PRIMARY' => array('column' => 'quest_id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'raids' => array(
					'raid_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 5, 'key' => 'primary'),
					'raid_name' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 100, 'collate' => 'utf8_general_ci', 'comment' => 'レイドイベント名', 'charset' => 'utf8'),
					'start_time' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'end_time' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 4),
					'indexes' => array(
						'PRIMARY' => array('column' => 'raid_id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'rank_ev_battle' => array(
					'rank_ev_battle_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'rank' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'comment' => '順位'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index'),
					'point' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'unit' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'comment' => 'ポイントの単位', 'charset' => 'utf8'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'rank_ev_battle_id', 'unique' => 1),
						'FK_rank_ev_battle_users' => array('column' => 'user_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'rank_ev_raid' => array(
					'rank_ev_raid_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'rank' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'comment' => '順位'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index'),
					'point' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'unit' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'comment' => 'ポイントの単位', 'charset' => 'utf8'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'rank_ev_raid_id', 'unique' => 1),
						'FK_rank_raid_event_users' => array('column' => 'user_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'skills' => array(
					'skill_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'skill_name' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'effect' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'comment' => '1:def 2:atk'),
					'updown' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 3, 'comment' => '1:up 2:down'),
					'target' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 3, 'comment' => '1:自分 2:相手　3.味方 4.相手全体'),
					'percent' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'comment' => '相手のatkを何％下げるなど'),
					'skill_words' => array('type' => 'string', 'null' => false, 'default' => '0', 'length' => 60, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'indexes' => array(
						'PRIMARY' => array('column' => 'skill_id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'sns_users' => array(
					'sns_user_id' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'key' => 'primary', 'collate' => 'utf8_general_ci', 'comment' => 'opensocial_owner_id', 'charset' => 'utf8'),
					'viewer' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'comment' => 'opensocial_viewer_id', 'charset' => 'utf8'),
					'sns_name' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'comment' => 'SNS側の名前', 'charset' => 'utf8'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 4),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'sns_user_id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'stage_probs' => array(
					'stage_prob_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'stage_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'key' => 'index'),
					'raid_id' => array('type' => 'integer', 'null' => false, 'default' => '1', 'length' => 5, 'comment' => '1:通常クエスト 2:レイドイベントID'),
					'kind' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'comment' => '1:card 2:item 3:money 4:enemy 5:全力進行 6:出会い'),
					'target' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'comment' => '対象のID'),
					'num' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'comment' => '数量'),
					'prob' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'indexes' => array(
						'PRIMARY' => array('column' => 'stage_prob_id', 'unique' => 1),
						'stage_id' => array('column' => 'stage_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'stages' => array(
					'stage_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 5, 'key' => 'primary'),
					'quest_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'key' => 'index'),
					'stage_title' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'use_act' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'comment' => '消費行動力'),
					'prob_get' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'comment' => '何かを取得する確率'),
					'enemy_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index', 'comment' => 'ステージのボス'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'indexes' => array(
						'PRIMARY' => array('column' => 'stage_id', 'unique' => 1),
						'FK_mst_stages_mst_enemy' => array('column' => 'enemy_id', 'unique' => 0),
						'FK_stages_quests' => array('column' => 'quest_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'static_pages' => array(
					'static_page_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'page' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'key' => 'unique', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'static_page_title' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'static_page_detail' => array('type' => 'text', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 4),
					'indexes' => array(
						'PRIMARY' => array('column' => 'static_page_id', 'unique' => 1),
						'page' => array('column' => 'page', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'tutorials' => array(
					'tutorial_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 5, 'key' => 'primary'),
					'tutorial_title' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'tutorial_words' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 1000, 'collate' => 'utf8_general_ci', 'comment' => '案内キャラのセリフ', 'charset' => 'utf8'),
					'tutorial_words2' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 1000, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'tutorial_words3' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 1000, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'tutorial_next' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'comment' => '次のID'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'indexes' => array(
						'PRIMARY' => array('column' => 'tutorial_id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_base_cards' => array(
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'primary'),
					'user_card_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'user_id', 'unique' => 1),
						'FK__user_cards' => array('column' => 'user_card_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_boxs' => array(
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'primary'),
					'user_item_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'primary', 'comment' => 'ユーザーのどの金庫か'),
					'kind' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'key' => 'primary'),
					'target' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'key' => 'primary'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => array('user_id', 'user_item_id', 'kind', 'target'), 'unique' => 1),
						'FK_user_boxs_user_items' => array('column' => 'user_item_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_cards' => array(
					'user_card_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index'),
					'card_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index'),
					'hp' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'hp_max' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'atk' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'def' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'level' => array('type' => 'integer', 'null' => false, 'default' => '1', 'length' => 5),
					'exp' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'skill_level' => array('type' => 'integer', 'null' => false, 'default' => '1', 'length' => 5),
					'skill_exp' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'user_card_id', 'unique' => 1),
						'card_id' => array('column' => 'card_id', 'unique' => 0),
						'user_card_id' => array('column' => array('user_id', 'card_id'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_collects' => array(
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'primary'),
					'card_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'primary'),
					'new_flg' => array('type' => 'integer', 'null' => false, 'default' => '1', 'length' => 3, 'comment' => '閲覧すれば0'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => array('user_id', 'card_id'), 'unique' => 1),
						'FK_user_collects_cards' => array('column' => 'card_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_cur_stages' => array(
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'primary'),
					'stage_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'key' => 'index'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'user_id', 'unique' => 1),
						'FK_user_cur_stages_stages' => array('column' => 'stage_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_deck_cards' => array(
					'user_deck_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'primary'),
					'deck_number' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 2, 'key' => 'primary', 'comment' => '1から5まで'),
					'user_card_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => array('user_deck_id', 'deck_number'), 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_decks' => array(
					'user_deck_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index'),
					'kind' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'comment' => '1:攻撃デッキ 2:防御デッキ'),
					'user_deck_name' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'user_deck_id', 'unique' => 1),
						'FK_user_decks_users' => array('column' => 'user_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_ev_stages' => array(
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'primary'),
					'ev_stage_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 8, 'key' => 'index'),
					'progress' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'comment' => '最大100'),
					'state' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'comment' => '1:進行中 2:達成 3:ボス勝利'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'user_id', 'unique' => 1),
						'user_ev_stage_id' => array('column' => array('user_id', 'ev_stage_id'), 'unique' => 0),
						'FK_user_ev_stages_ev_stages' => array('column' => 'ev_stage_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_gacha_days' => array(
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'primary'),
					'gacha_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'key' => 'index'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'user_id', 'unique' => 1),
						'FK_user_gacha_days_gachas' => array('column' => 'gacha_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_gacha_logs' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => true, 'default' => null, 'length' => 10),
					'gacha_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'key' => 'index'),
					'card_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index'),
					'end_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'FK_user_gacha_logs_gachas' => array('column' => 'gacha_id', 'unique' => 0),
						'FK_user_gacha_logs_cards' => array('column' => 'card_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_items' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index'),
					'item_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'key' => 'index'),
					'num' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'comment' => '所持個数'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'user_id' => array('column' => array('user_id', 'item_id'), 'unique' => 1),
						'FK_user_items_items' => array('column' => 'item_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_last_act_times' => array(
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'primary'),
					'delete_flg' => array('type' => 'integer', 'null' => true, 'default' => '0', 'length' => 3),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'user_id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_login_all_logs' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index'),
					'kind' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'comment' => '1:card 2:item 3:money 4:enemy'),
					'target' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'FK_user_login_all_log_users' => array('column' => 'user_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_login_days' => array(
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'primary'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'user_id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_login_logs' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index'),
					'kind' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'comment' => '1:card 2:item 3:money 4:enemy'),
					'target' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'FK_user_login_log_users' => array('column' => 'user_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_params' => array(
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'primary', 'comment' => 'usersのid'),
					'money' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'comment' => 'ゲーム内通貨'),
					'act' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'comment' => '行動力'),
					'act_max' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'comment' => '行動力最大値'),
					'cost_atk' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 6, 'comment' => '攻撃デッキコスト'),
					'cost_def' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'comment' => '防御デッキコスト'),
					'level' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'comment' => 'レベル'),
					'exp' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'comment' => '経験値'),
					'win' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'comment' => 'バトル勝利数'),
					'lose' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'comment' => 'バトル敗北数'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'user_id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_present_boxs' => array(
					'user_present_box_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index'),
					'kind' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'comment' => '1:card 2:item 3:money 4:enemy'),
					'target' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10),
					'num' => array('type' => 'integer', 'null' => false, 'default' => '1', 'length' => 10, 'comment' => 'お金の場合は金額'),
					'message' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'user_present_box_id', 'unique' => 1),
						'index_1' => array('column' => 'user_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_profs' => array(
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'primary'),
					'prof' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 250, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'user_id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_raid_logs' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index', 'comment' => '攻撃者'),
					'user_raid_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index', 'comment' => '対象のレイドボス'),
					'damage' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'comment' => '与えたダメージ合計'),
					'win_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'comment' => '1:とどめをさした場合'),
					'log' => array('type' => 'text', 'null' => false, 'default' => null, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'updated' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'FK_user_raid_logs_users' => array('column' => 'user_id', 'unique' => 0),
						'FK_user_raid_logs_user_raids' => array('column' => 'user_raid_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_raids' => array(
					'user_raid_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index', 'comment' => '発見者'),
					'raid_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'key' => 'index', 'comment' => 'レイドイベントID'),
					'enemy_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'index'),
					'hp' => array('type' => 'integer', 'null' => false, 'default' => '0', 'comment' => '対象の残りHP'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'updated' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'user_raid_id', 'unique' => 1),
						'user_raid_id' => array('column' => array('user_id', 'raid_id'), 'unique' => 0),
						'FK_user_raids_raids' => array('column' => 'raid_id', 'unique' => 0),
						'FK_user_raids_enemys' => array('column' => 'enemy_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_stages' => array(
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'primary'),
					'stage_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'key' => 'primary'),
					'progress' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'comment' => '最大100'),
					'state' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3, 'comment' => '1:進行中 2:達成 3:ボス勝利'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => array('user_id', 'stage_id'), 'unique' => 1),
						'FK_user_stages_stages' => array('column' => 'stage_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'user_tutorials' => array(
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 10, 'key' => 'primary'),
					'tutorial_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 5, 'key' => 'index'),
					'end_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'user_id', 'unique' => 1),
						'FK_user_tutorials_tutorials' => array('column' => 'tutorial_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'users' => array(
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 10, 'key' => 'primary'),
					'user_name' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'sns_user_id' => array('type' => 'string', 'null' => false, 'default' => null, 'length' => 50, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'carrer' => array('type' => 'integer', 'null' => false, 'default' => null, 'length' => 3, 'comment' => '1.android 2.iphone'),
					'delete_flg' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 3),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => null),
					'indexes' => array(
						'PRIMARY' => array('column' => 'user_id', 'unique' => 1),
						'sns_user_id' => array('column' => 'sns_user_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
			),
		),
		'down' => array(
			'drop_table' => array(
				'battle_logs', 'card_groups', 'cards', 'enemys', 'errors', 'ev_item_probs', 'ev_quests', 'ev_stage_probs', 'ev_stages', 'ev_user_cur_stages', 'friends', 'gacha_probs', 'gachas', 'item_effects', 'item_probs', 'items', 'messages', 'news', 'quests', 'raids', 'rank_ev_battle', 'rank_ev_raid', 'skills', 'sns_users', 'stage_probs', 'stages', 'static_pages', 'tutorials', 'user_base_cards', 'user_boxs', 'user_cards', 'user_collects', 'user_cur_stages', 'user_deck_cards', 'user_decks', 'user_ev_stages', 'user_gacha_days', 'user_gacha_logs', 'user_items', 'user_last_act_times', 'user_login_all_logs', 'user_login_days', 'user_login_logs', 'user_params', 'user_present_boxs', 'user_profs', 'user_raid_logs', 'user_raids', 'user_stages', 'user_tutorials', 'users'
			),
		),
	);

/**
 * Before migration callback
 *
 * @param string $direction, up or down direction of migration process
 * @return boolean Should process continue
 */
	public function before($direction) {
		return true;
	}

/**
 * After migration callback
 *
 * @param string $direction, up or down direction of migration process
 * @return boolean Should process continue
 */
	public function after($direction) {
		return true;
	}
}
